cors:
  origins:
    - http://localhost:4000
    - https://studio.apollographql.com
  allow_credentials: true
  allow_headers:
    - Content-Type
    - Authorization
  methods:
    - GET
    - POST
    - PUT
    - DELETE
  expose_headers:
    - Content-Length
    - X-Content-Length
  max_age: 3600
